////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                        //
//         This program is the confidential and proprietary product of IAV GmbH.          //
// Any unauthorised use, reproduction or transfer of this program is strictly prohibited. //
//                                  Copyright IAV GmbH.                                   //
//             (Subject to limited distribution and restricted disclosure only.)          //
//                                   All rights reserved.                                 //
//                                                                                        //
////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                        //
// This file is generated by IDLCodeGenPy 1.11.1                                          //
//                                                                                        //
// Please do not modify this file by hand!                                                //
//                                                                                        //
////////////////////////////////////////////////////////////////////////////////////////////


#ifndef __HEADER_DECL_H__
#define __HEADER_DECL_H__


#include "topic_includes.h"

#include "Time.h"

#define __std_msgs__msg__Header__idl 

#define IDL_HASH_HEADER 0x29768e62e4e9d15fULL


namespace std_msgs {

    namespace msg {


#define std_msgs_msg_Header_isPODType 0

//---------------------------------------------------------------------------
//! \class Header
//!
//! \brief 
//
class Header
{
public:
    //! \brief Constructor
    Header();
    //! \brief Destructor
    ~Header();

    //! \brief Copy constructor
    Header(const std_msgs::msg::Header &other);

    //! \brief Assignment operator
    std_msgs::msg::Header& operator=(const std_msgs::msg::Header &other);
#ifndef IDL_NO_PTR_ASSIGNMENT_OP
    //! \brief Assignment operator for pointer source
    inline std_msgs::msg::Header& operator=(const std_msgs::msg::Header *other) { *this = *other; return *this; }
#endif

    //! \brief Calculates how many bytes will be needed to serialize the object in its current state.
    std::size_t getSerializedSize() const;

    //! \brief Serialize data into 'buffer'. The buffer needs to have at least the size that getSerializedSize() returns.
    std::size_t serialize(void *buffer) const;

    //! \brief Deserialize data from buffer. The buffer needs to have at least the size that getSerializedSize() returns.
    std::size_t deserialize(const void *buffer);

    //! \brief Indicator function to signal that the class is purely made of simple data types
    static bool isPODType() { return false; }


public:
    std_msgs::msg::Time stamp;                 
    std::string frame_id;                      
}; // struct: Header

} // ns: msg

} // ns: std_msgs


#endif // __HEADER_DECL_H__

