////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                        //
//         This program is the confidential and proprietary product of IAV GmbH.          //
// Any unauthorised use, reproduction or transfer of this program is strictly prohibited. //
//                                  Copyright IAV GmbH.                                   //
//             (Subject to limited distribution and restricted disclosure only.)          //
//                                   All rights reserved.                                 //
//                                                                                        //
////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                        //
// This file is generated by IDLCodeGenPy 1.11.1                                          //
//                                                                                        //
// Please do not modify this file by hand!                                                //
//                                                                                        //
////////////////////////////////////////////////////////////////////////////////////////////


#ifndef __TIME_DECL_H__
#define __TIME_DECL_H__


#include "topic_includes.h"


#define __std_msgs__msg__Time__idl 

#define IDL_HASH_TIME 0xfdc812affa11d908ULL


namespace std_msgs {

    namespace msg {


#define std_msgs_msg_Time_isPODType 1

//---------------------------------------------------------------------------
//! \class Time
//!
//! \brief 
//
class Time
{
public:
    //! \brief Constructor
    Time();
    //! \brief Destructor
    ~Time();

    //! \brief Copy constructor
    Time(const std_msgs::msg::Time &other);

    //! \brief Assignment operator
    std_msgs::msg::Time& operator=(const std_msgs::msg::Time &other);
#ifndef IDL_NO_PTR_ASSIGNMENT_OP
    //! \brief Assignment operator for pointer source
    inline std_msgs::msg::Time& operator=(const std_msgs::msg::Time *other) { *this = *other; return *this; }
#endif

    //! \brief Calculates how many bytes will be needed to serialize the object in its current state.
    std::size_t getSerializedSize() const;

    //! \brief Serialize data into 'buffer'. The buffer needs to have at least the size that getSerializedSize() returns.
    std::size_t serialize(void *buffer) const;

    //! \brief Deserialize data from buffer. The buffer needs to have at least the size that getSerializedSize() returns.
    std::size_t deserialize(const void *buffer);

    //! \brief Indicator function to signal that the class is purely made of simple data types
    static bool isPODType() { return true; }


public:
    int32_t sec;                               
    uint32_t nanosec;                          
}; // struct: Time

} // ns: msg

} // ns: std_msgs


#endif // __TIME_DECL_H__

