////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                        //
//         This program is the confidential and proprietary product of IAV GmbH.          //
// Any unauthorised use, reproduction or transfer of this program is strictly prohibited. //
//                                  Copyright IAV GmbH.                                   //
//             (Subject to limited distribution and restricted disclosure only.)          //
//                                   All rights reserved.                                 //
//                                                                                        //
////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                        //
// This file is generated by Bonnie 3.1.1                                                 //
//                                                                                        //
////////////////////////////////////////////////////////////////////////////////////////////

#ifndef __FEATURELOCALISATION_VERSION_H__
#define __FEATURELOCALISATION_VERSION_H__

#ifndef ADPL_MODULE_VERSION_LABEL
    #define ADPL_MODULE_VERSION_LABEL "(C) IAV build " __DATE__ " " __TIME__
#endif

// define the module's version
namespace ModuleVersion
{
	namespace FeatureLocalisation
	{
		const int32_t major  = 1;
		const int32_t minor  = 0;
		const int32_t bugfix = 0;
		const char version_label[] = ADPL_MODULE_VERSION_LABEL;
	}
}

#endif // __FEATURELOCALISATION_VERSION_H__
