////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                        //
//         This program is the confidential and proprietary product of IAV GmbH.          //
// Any unauthorised use, reproduction or transfer of this program is strictly prohibited. //
//                                  Copyright IAV GmbH.                                   //
//             (Subject to limited distribution and restricted disclosure only.)          //
//                                   All rights reserved.                                 //
//                                                                                        //
////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                        //
// This file is generated by IDLCodeGenPy 1.11.1                                          //
//                                                                                        //
// Please do not modify this file by hand!                                                //
//                                                                                        //
////////////////////////////////////////////////////////////////////////////////////////////


#ifndef __NAVSATFIX_DECL_H__
#define __NAVSATFIX_DECL_H__


#include "topic_includes.h"

#include "NavSatStatus.h"
#include "std_msgs/msg/Header.h"

#define __sensor_msgs__msg__NavSatFix__idl

#define IDL_HASH_NAVSATFIX 0xefbdb550cf551393ULL


namespace sensor_msgs {

    namespace msg {
        const uint8_t NavSatFix__COVARIANCE_TYPE_UNKNOWN = 0;
        const uint8_t NavSatFix__COVARIANCE_TYPE_APPROXIMATED = 1;
        const uint8_t NavSatFix__COVARIANCE_TYPE_DIAGONAL_KNOWN = 2;
        const uint8_t NavSatFix__COVARIANCE_TYPE_KNOWN = 3;

        typedef std::array<double, 9> sensor_msgs__NavSatFix__double_array_9;


#define sensor_msgs_msg_NavSatFix_isPODType 1

//---------------------------------------------------------------------------
//! \class NavSatFix
//!
//! \brief
//
class NavSatFix
{
public:
    //! \brief Constructor
    NavSatFix();
    //! \brief Destructor
    ~NavSatFix();

    //! \brief Copy constructor
    NavSatFix(const sensor_msgs::msg::NavSatFix &other);

    //! \brief Assignment operator
    sensor_msgs::msg::NavSatFix& operator=(const sensor_msgs::msg::NavSatFix &other);
#ifndef IDL_NO_PTR_ASSIGNMENT_OP
    //! \brief Assignment operator for pointer source
    inline sensor_msgs::msg::NavSatFix& operator=(const sensor_msgs::msg::NavSatFix *other) { *this = *other; return *this; }
#endif

    //! \brief Calculates how many bytes will be needed to serialize the object in its current state.
    std::size_t getSerializedSize() const;

    //! \brief Serialize data into 'buffer'. The buffer needs to have at least the size that getSerializedSize() returns.
    std::size_t serialize(void *buffer) const;

    //! \brief Deserialize data from buffer. The buffer needs to have at least the size that getSerializedSize() returns.
    std::size_t deserialize(const void *buffer);

    //! \brief Indicator function to signal that the class is purely made of simple data types
    static bool isPODType() { return true; }


public:
    std_msgs::msg::Header header;
    sensor_msgs::msg::NavSatStatus status;
    double latitude;
    double longitude;
    double altitude;
    sensor_msgs__NavSatFix__double_array_9 position_covariance;
    uint8_t position_covariance_type;
}; // struct: NavSatFix

} // ns: msg

} // ns: sensor_msgs


#endif // __NAVSATFIX_DECL_H__

