////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                        //
//         This program is the confidential and proprietary product of IAV GmbH.          //
// Any unauthorised use, reproduction or transfer of this program is strictly prohibited. //
//                                  Copyright IAV GmbH.                                   //
//             (Subject to limited distribution and restricted disclosure only.)          //
//                                   All rights reserved.                                 //
//                                                                                        //
////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                        //
// This file is generated by IDLCodeGenPy 1.11.1                                          //
//                                                                                        //
// Please do not modify this file by hand!                                                //
//                                                                                        //
////////////////////////////////////////////////////////////////////////////////////////////


#ifndef __ODOMETRY_DECL_H__
#define __ODOMETRY_DECL_H__


#include "topic_includes.h"

#include "geometry_msgs/msg/PoseWithCovariance.h"
#include "geometry_msgs/msg/TwistWithCovariance.h"
#include "std_msgs/msg/Header.h"

#define __nav_msgs__msg__Odometry__idl 

#define IDL_HASH_ODOMETRY 0x68903aa7da9bac91ULL


namespace nav_msgs {

    namespace msg {


#define nav_msgs_msg_Odometry_isPODType 0

//---------------------------------------------------------------------------
//! \class Odometry
//!
//! \brief 
//
class Odometry
{
public:
    //! \brief Constructor
    Odometry();
    //! \brief Destructor
    ~Odometry();

    //! \brief Copy constructor
    Odometry(const nav_msgs::msg::Odometry &other);

    //! \brief Assignment operator
    nav_msgs::msg::Odometry& operator=(const nav_msgs::msg::Odometry &other);
#ifndef IDL_NO_PTR_ASSIGNMENT_OP
    //! \brief Assignment operator for pointer source
    inline nav_msgs::msg::Odometry& operator=(const nav_msgs::msg::Odometry *other) { *this = *other; return *this; }
#endif

    //! \brief Calculates how many bytes will be needed to serialize the object in its current state.
    std::size_t getSerializedSize() const;

    //! \brief Serialize data into 'buffer'. The buffer needs to have at least the size that getSerializedSize() returns.
    std::size_t serialize(void *buffer) const;

    //! \brief Deserialize data from buffer. The buffer needs to have at least the size that getSerializedSize() returns.
    std::size_t deserialize(const void *buffer);

    //! \brief Indicator function to signal that the class is purely made of simple data types
    static bool isPODType() { return false; }


public:
    std_msgs::msg::Header header;              
    std::string child_frame_id;                
    geometry_msgs::msg::PoseWithCovariance pose;
    geometry_msgs::msg::TwistWithCovariance twist;
}; // struct: Odometry

} // ns: msg

} // ns: nav_msgs


#endif // __ODOMETRY_DECL_H__

