////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                        //
//         This program is the confidential and proprietary product of IAV GmbH.          //
// Any unauthorised use, reproduction or transfer of this program is strictly prohibited. //
//                                  Copyright IAV GmbH.                                   //
//             (Subject to limited distribution and restricted disclosure only.)          //
//                                   All rights reserved.                                 //
//                                                                                        //
////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                        //
// This file is generated by IDLCodeGenPy 1.11.1                                          //
//                                                                                        //
// Please do not modify this file by hand!                                                //
//                                                                                        //
////////////////////////////////////////////////////////////////////////////////////////////


#ifndef __POINT_DECL_H__
#define __POINT_DECL_H__


#include "topic_includes.h"


#define __geometry_msgs__msg__Point__idl 

#define IDL_HASH_POINT 0x22e4cc7078aa5037ULL


namespace geometry_msgs {

    namespace msg {


#define geometry_msgs_msg_Point_isPODType 1

//---------------------------------------------------------------------------
//! \class Point
//!
//! \brief 
//
class Point
{
public:
    //! \brief Constructor
    Point();
    //! \brief Destructor
    ~Point();

    //! \brief Copy constructor
    Point(const geometry_msgs::msg::Point &other);

    //! \brief Assignment operator
    geometry_msgs::msg::Point& operator=(const geometry_msgs::msg::Point &other);
#ifndef IDL_NO_PTR_ASSIGNMENT_OP
    //! \brief Assignment operator for pointer source
    inline geometry_msgs::msg::Point& operator=(const geometry_msgs::msg::Point *other) { *this = *other; return *this; }
#endif

    //! \brief Calculates how many bytes will be needed to serialize the object in its current state.
    std::size_t getSerializedSize() const;

    //! \brief Serialize data into 'buffer'. The buffer needs to have at least the size that getSerializedSize() returns.
    std::size_t serialize(void *buffer) const;

    //! \brief Deserialize data from buffer. The buffer needs to have at least the size that getSerializedSize() returns.
    std::size_t deserialize(const void *buffer);

    //! \brief Indicator function to signal that the class is purely made of simple data types
    static bool isPODType() { return true; }


public:
    double x;                                  
    double y;                                  
    double z;                                  
}; // struct: Point

} // ns: msg

} // ns: geometry_msgs


#endif // __POINT_DECL_H__

