////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                        //
//         This program is the confidential and proprietary product of IAV GmbH.          //
// Any unauthorised use, reproduction or transfer of this program is strictly prohibited. //
//                                  Copyright IAV GmbH.                                   //
//             (Subject to limited distribution and restricted disclosure only.)          //
//                                   All rights reserved.                                 //
//                                                                                        //
////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                        //
// This file is generated by IDLCodeGenPy 1.11.1                                          //
//                                                                                        //
// Please do not modify this file by hand!                                                //
//                                                                                        //
////////////////////////////////////////////////////////////////////////////////////////////


#ifndef __TWIST_DECL_H__
#define __TWIST_DECL_H__


#include "topic_includes.h"

#include "Vector3.h"

#define __geometry_msgs__msg__Twist__idl 

#define IDL_HASH_TWIST 0x4895398f50a09645ULL


namespace geometry_msgs {

    namespace msg {


#define geometry_msgs_msg_Twist_isPODType 1

//---------------------------------------------------------------------------
//! \class Twist
//!
//! \brief 
//
class Twist
{
public:
    //! \brief Constructor
    Twist();
    //! \brief Destructor
    ~Twist();

    //! \brief Copy constructor
    Twist(const geometry_msgs::msg::Twist &other);

    //! \brief Assignment operator
    geometry_msgs::msg::Twist& operator=(const geometry_msgs::msg::Twist &other);
#ifndef IDL_NO_PTR_ASSIGNMENT_OP
    //! \brief Assignment operator for pointer source
    inline geometry_msgs::msg::Twist& operator=(const geometry_msgs::msg::Twist *other) { *this = *other; return *this; }
#endif

    //! \brief Calculates how many bytes will be needed to serialize the object in its current state.
    std::size_t getSerializedSize() const;

    //! \brief Serialize data into 'buffer'. The buffer needs to have at least the size that getSerializedSize() returns.
    std::size_t serialize(void *buffer) const;

    //! \brief Deserialize data from buffer. The buffer needs to have at least the size that getSerializedSize() returns.
    std::size_t deserialize(const void *buffer);

    //! \brief Indicator function to signal that the class is purely made of simple data types
    static bool isPODType() { return true; }


public:
    geometry_msgs::msg::Vector3 linear;        
    geometry_msgs::msg::Vector3 angular;       
}; // struct: Twist

} // ns: msg

} // ns: geometry_msgs


#endif // __TWIST_DECL_H__

