////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                        //
//         This program is the confidential and proprietary product of IAV GmbH.          //
// Any unauthorised use, reproduction or transfer of this program is strictly prohibited. //
//                                  Copyright IAV GmbH.                                   //
//             (Subject to limited distribution and restricted disclosure only.)          //
//                                   All rights reserved.                                 //
//                                                                                        //
////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                        //
// This file is generated by IDLCodeGenPy 1.11.1                                          //
//                                                                                        //
// Please do not modify this file by hand!                                                //
//                                                                                        //
////////////////////////////////////////////////////////////////////////////////////////////


#include "geometry_msgs/msg/Point.h"
#include "geometry_msgs/msg/Quaternion.h"
#include "geometry_msgs/msg/Pose.h"


namespace geometry_msgs
{
namespace msg
{

std::size_t Pose::serialize(void *pOutput) const
{
    if (!pOutput)
        return 0;
    uint8_t *buf = (uint8_t*)pOutput;

    buf += position.serialize(buf); // Point
    buf += orientation.serialize(buf); // Quaternion

    return static_cast<std::size_t>(buf - (uint8_t*)pOutput);
}

std::size_t Pose::deserialize(const void *pInput)
{
    if (!pInput)
        return 0;

    const uint8_t *buf = (const uint8_t*)pInput;


    buf += position.deserialize(buf); // Simple member position: Point
    buf += orientation.deserialize(buf); // Simple member orientation: Quaternion
    return static_cast<uint32_t>(buf - (uint8_t*)pInput);
}

//! \brief default ctor
Pose::Pose()
{



}

//! \brief dtor
Pose::~Pose()
{


}

//! \brief Copy constructor
Pose::Pose(const geometry_msgs::msg::Pose &other)
{

    position = other.position;
    orientation = other.orientation;}

std::size_t Pose::getSerializedSize() const
{
	std::size_t _size_ = 0;

    _size_ += position.getSerializedSize();
    _size_ += orientation.getSerializedSize();
    return _size_;
}

#ifndef IDL_NO_PTR_ASSIGNMENT_OP
geometry_msgs::msg::Pose& Pose::operator=(const geometry_msgs::msg::Pose &other)
{
    if (this != &other)
    {
        position = other.position;
        orientation = other.orientation;
    }
    return *this;
}
#endif //IDL_NO_PTR_ASSIGNMENT_OP
} // ns: msg

} // ns: geometry_msgs

