////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                        //
//         This program is the confidential and proprietary product of IAV GmbH.          //
// Any unauthorised use, reproduction or transfer of this program is strictly prohibited. //
//                                  Copyright IAV GmbH.                                   //
//             (Subject to limited distribution and restricted disclosure only.)          //
//                                   All rights reserved.                                 //
//                                                                                        //
////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                        //
// This file is generated by IDLCodeGenPy 1.11.1                                          //
//                                                                                        //
// Please do not modify this file by hand!                                                //
//                                                                                        //
////////////////////////////////////////////////////////////////////////////////////////////


#include "geometry_msgs/msg/Pose.h"
#include "geometry_msgs/msg/PoseWithCovariance.h"


namespace geometry_msgs
{
namespace msg
{

std::size_t PoseWithCovariance::serialize(void *pOutput) const
{
    if (!pOutput)
        return 0;
    uint8_t *buf = (uint8_t*)pOutput;

    buf += pose.serialize(buf); // Pose
    *(geometry_msgs__PoseWithCovariance__double_array_36*)buf = covariance;
    //buf += None;

    return static_cast<std::size_t>(buf - (uint8_t*)pOutput);
}

std::size_t PoseWithCovariance::deserialize(const void *pInput)
{
    if (!pInput)
        return 0;

    const uint8_t *buf = (const uint8_t*)pInput;


    buf += pose.deserialize(buf); // Simple member pose: Pose
    covariance = *reinterpret_cast<const geometry_msgs__PoseWithCovariance__double_array_36*>(buf);
 /*   buf += None;*/
    return static_cast<uint32_t>(buf - (uint8_t*)pInput);
}

//! \brief default ctor
PoseWithCovariance::PoseWithCovariance()
{


    //covariance = 0;
}

//! \brief dtor
PoseWithCovariance::~PoseWithCovariance()
{


}

//! \brief Copy constructor
PoseWithCovariance::PoseWithCovariance(const geometry_msgs::msg::PoseWithCovariance &other)
{

    pose = other.pose;
    covariance = other.covariance;}

std::size_t PoseWithCovariance::getSerializedSize() const
{
	std::size_t _size_ = 0;

    _size_ += pose.getSerializedSize();
    //_size_ += None;
    return _size_;
}

#ifndef IDL_NO_PTR_ASSIGNMENT_OP
geometry_msgs::msg::PoseWithCovariance& PoseWithCovariance::operator=(const geometry_msgs::msg::PoseWithCovariance &other)
{
    if (this != &other)
    {
        pose = other.pose;
        covariance = other.covariance;
    }
    return *this;
}
#endif //IDL_NO_PTR_ASSIGNMENT_OP
} // ns: msg

} // ns: geometry_msgs

